### list all employee metadata

GET http://localhost:3000/employee/metadata


#### metadata search
POST http://localhost:3000/employee/metadata
Content-Type: application/json

{ 
    "text": 1
}

#### create new employee
POST http://localhost:3000/employee
Content-Type: application/json

{ 
    "firstName": "Muffin",
    "lastName": "Charles",
    "title": "Programmer",
    "department": "IT",
    "hiredDate": "2008-08-27T00:00:00.000Z",
    "salary": 70000
}