### list all employees 

GET http://localhost:3000/employee/metadata


#### create new employee
POST http://localhost:3000/employee
Content-Type: application/json

{ 
    "firstName": "Barry",
    "lastName": "Moss",
    "title": "Janitor",
    "department": "Maintenance",
    "hiredDate": "2011-08-27T00:00:00.000Z",
    "salary": 20000
}