POST http://localhost:3000/product/create
Content-Type: application/json

{
    "name": "blender",
    "department": "kitchen",
    "category": "electrics",
    "brand": "Ninja",
    "last_shipment_date": "2021-08-13T09:22:37.926Z",
    "quantity_in_stock": 200,
    "price": 75,
    "isAvailable": true
}

#### get all products

GET http://localhost:3000/product

#### find one product by id

GET http://localhost:3000/product/7